version: '3'
services:
  frontend:
    container_name: udgfront
    build: .
    volumes:
      - ./dist:/app/dist
    command: npm run build
    deploy:
      resources:
        limits:
          memory: 200M
  web:
    image: httpd
    volumes:
      - ./dist:/usr/local/apache2/htdocs/
    ports:
      - 80:80
    depends_on:
      - frontend